### PR TITLE
Fix broken sentence in about.html

### LINKED ISSUE #150: Incomplete sentence in copy on About page
About page copy includes typo (incomplete sentence) in 3rd sentence in first paragraph:

"MuseumStat is a robust online resource to support museums, communities, and researchers in gaining insights into the reach of museums and the communities they serve. MuseumStat contains information on about 30,000 organizations in the Institute of Museum and Library Services’ Museum Universe Data File (MUDF). **The museum data are combined with community metrics on every U.S. census tract in the.** MuseumStat is built on a geographical information system (GIS) platform that is designed to be intuitive and useful to a wide range of users and will continue to grow in its scope of features and information."

### PR DESCRIPTION
**Pull request by CloudNiner**
@nevillevak can you review quick and make sure this matches what you expect?

Closes #150

### CODE REVIEW

**Comment by nevillevak** [comment]
@CloudNiner - The updated text does not appear to be on the live page. It still shows the incomplete sentence. Is there somewhere else I should be looking? Please advise.

**Comment by CloudNiner** [comment]
Ah, sorry if that was unclear. The change is in the "files changed" tab of this pull request, make sure the text in the green line there matches what you would expect. I haven't pushed the update yet.

**Comment by nevillevak** [comment]
Hi. Thanks for clarifying. Now that I see the full text, the sentence should read:
"The museum data are combined with community metrics on every census tract in the United States." (We don't need "U.S." between the words "every" and "census")

**Comment by CloudNiner** [comment]
Thanks for taking a look. Updated again, going to merge this and then deploy sometime before tomorrow am.

**Comment by nevillevak** [comment]
Great. Also note that we still need to add "United States" at the end of that sentence. Sorry to make something so simple so complicated!

**Comment by CloudNiner** [comment]
Right. So this screenshot is correct, yes?

screen shot 2017-01-23 at 14 44 21

**Comment by nevillevak** [comment]
Yes. Thanks!

Best,
Neville
________________________________
Neville K. Vakharia
Assistant Professor and Research Director
Drexel University, Westphal College of Media Arts & Design
Department of Arts & Entertainment Enterprise
215.571.4439, nvakharia@drexel.edu

Office Hours:
Tuesdays and Thursdays, 2:00 – 5:00
By appointment only

**Pull request merged**
